name: build

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'UPGRADE.md'
      - '.gitignore'
      - '.gitattributes'

  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - 'UPGRADE.md'
      - '.gitignore'
      - '.gitattributes'

env:
  COMPOSE_PROJECT_NAME: yii2-queue
  COMPOSE_FILE: tests/docker-compose.yml

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1', '8.2']

    steps:
      - name: Checkout.
        uses: actions/checkout@v4

      - name: PHP Unit tests for PHP ${{ matrix.php }}
        run: make test v=${{ matrix.php }}

      - name: Upload coverage to Codecov.
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
